#!/usr/bin/env python

# Author : Phidica Veia
# Create : 2015-10-01

# This is a support script for the mcserver Bash script. If you want to though, you can make it executable with "chmod +x mcserver-motd" and use it as described in the usage

import sys, getopt
from pyjavaproperties import Properties

def showUsage():
  print "Usage: mcserver-motd <infile.properties> -g"
  print "   or: mcserver-motd <infile.properties> -s <\"new message\">"
  print "For the given file, get the current MotD or set a new one"

def main(infile, argv):
  if len(argv) == 0:
    showUsage()
    sys.exit(2)

  try:
    opts, args = getopt.getopt(argv, "hgs:")
  except getopt.GetoptError:
    showUsage()
    sys.exit(2)

  try:
    p = Properties()
    p.load(open(infile))
  except IOError as detail:
    sys.exit( "{} {}".format("mcserver-motd error:", detail) )

  for opt, arg in opts:
    if opt == "-g":
      print p["motd"]
    elif opt == "-s":
      p["motd"] = arg
    elif opt == "-h":
      showUsage()

  p.store(open(infile,"w"))

# Read the infile from the arguments, if possible
try:
  infile = sys.argv[1]
except IndexError:
  showUsage()
  sys.exit(2)

# Operate on the infile using all subsequent arguments
if __name__ == "__main__":
  main(infile, sys.argv[2:])

